# Generated by Django 4.0.3 on 2022-03-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
